"""
Copyright 2026 The Flame Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import argparse
import json
import os
import sys
import tempfile
import uuid
from contextlib import contextmanager
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Iterator, List, Optional, Sequence

import flamepy
from flamepy.runner.runner import Runner

DEFAULT_TASKS = 4


@dataclass(frozen=True)
class RunnerE2EResult:
    app_name: str
    template: str
    workdir: str
    function_results: List[int]
    chained_result: int
    stateful_result: int


def _positive_int(value: str) -> int:
    parsed = int(value)
    if parsed < 1:
        raise argparse.ArgumentTypeError("must be >= 1")
    return parsed


def _runner_template_name() -> str:
    ctx = flamepy.FlameContext()
    if ctx.runner is not None:
        return ctx.runner.template or "flmrun"
    return "flmrun"


@contextmanager
def _working_directory(path: Path) -> Iterator[None]:
    previous = os.getcwd()
    os.chdir(path)
    try:
        yield
    finally:
        os.chdir(previous)


@contextmanager
def _runner_project_dir(workdir: Optional[Path], keep_workdir: bool) -> Iterator[Path]:
    if workdir is not None:
        workdir.mkdir(parents=True, exist_ok=True)
        yield workdir
        return

    if keep_workdir:
        path = Path(tempfile.mkdtemp(prefix="flamepy-runner-e2e-"))
        yield path
        return

    with tempfile.TemporaryDirectory(prefix="flamepy-runner-e2e-") as tmpdir:
        yield Path(tmpdir)


def run_runner_e2e(
    name: Optional[str] = None,
    tasks: int = DEFAULT_TASKS,
    python_version: Optional[str] = None,
    dependencies: Optional[Sequence[str]] = None,
    workdir: Optional[Path] = None,
    keep_workdir: bool = False,
) -> RunnerE2EResult:
    if tasks < 1:
        raise ValueError("tasks must be >= 1")

    template = _runner_template_name()
    try:
        app = flamepy.get_application(template)
    except Exception as exc:
        raise RuntimeError(f"Runner template application {template!r} is not registered or the cluster is unreachable") from exc
    if app is None:
        raise RuntimeError(f"Runner template application {template!r} is not registered")

    app_name = name or f"flamepy-runner-e2e-{uuid.uuid4().hex[:8]}"

    def square(value: int) -> int:
        return value * value

    def add(left: int, right: int) -> int:
        return left + right

    class Counter:
        def __init__(self) -> None:
            self._value = 0

        def add(self, value: int) -> int:
            self._value += value
            return self._value

        def value(self) -> int:
            return self._value

    with _runner_project_dir(workdir, keep_workdir) as project_dir:
        readme_path = project_dir / "README.md"
        if not readme_path.exists():
            readme_path.write_text("Generated by flamepy.runner.e2e.\n", encoding="utf-8")
        with _working_directory(project_dir):
            with Runner(
                app_name,
                dependencies=list(dependencies or []),
                python_version=python_version,
            ) as runner:
                square_service: Any = runner.service(square)
                square_futures = [square_service(index) for index in range(tasks)]
                function_results = runner.get(square_futures)
                expected_results = [index * index for index in range(tasks)]
                if function_results != expected_results:
                    raise RuntimeError(f"function Runner check failed: expected {expected_results}, got {function_results}")

                add_service: Any = runner.service(add)
                chained_result = add_service(square_service(tasks), square_service(tasks + 1)).get()
                expected_chained = (tasks * tasks) + ((tasks + 1) * (tasks + 1))
                if chained_result != expected_chained:
                    raise RuntimeError(f"ObjectFuture chaining check failed: expected {expected_chained}, got {chained_result}")

                counter: Any = runner.service(Counter(), warmup=1)
                counter.add(2).wait()
                counter.add(4).wait()
                stateful_result = counter.value().get()
                if stateful_result != 6:
                    raise RuntimeError(f"stateful Runner instance check failed: expected 6, got {stateful_result}")

        return RunnerE2EResult(
            app_name=app_name,
            template=template,
            workdir=str(project_dir),
            function_results=function_results,
            chained_result=chained_result,
            stateful_result=stateful_result,
        )


def format_result(result: RunnerE2EResult) -> str:
    return "\n".join(
        [
            "Flame Runner cluster e2e passed",
            f"app: {result.app_name}",
            f"template: {result.template}",
            f"workdir: {result.workdir}",
            f"function results: {result.function_results}",
            f"ObjectFuture chained result: {result.chained_result}",
            f"stateful instance result: {result.stateful_result}",
        ]
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run a small Flame Runner workload against the configured cluster.")
    parser.add_argument("--name", help="Runner application name. Defaults to a unique flamepy-runner-e2e-* name.")
    parser.add_argument("--tasks", type=_positive_int, default=DEFAULT_TASKS, help=f"Number of function tasks to submit. Default: {DEFAULT_TASKS}.")
    parser.add_argument("--python-version", help="Python runtime version passed to Runner, for example 3.12.")
    parser.add_argument("--dependency", action="append", default=[], help="Additional package dependency for the generated Runner project. May be repeated.")
    parser.add_argument("--workdir", type=Path, help="Directory to package for the smoke workload. Defaults to a temporary directory.")
    parser.add_argument("--keep-workdir", action="store_true", help="Keep the generated temporary project directory after the run.")
    parser.add_argument("--json", action="store_true", dest="json_output", help="Print the result as JSON.")
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        result = run_runner_e2e(
            name=args.name,
            tasks=args.tasks,
            python_version=args.python_version,
            dependencies=args.dependency,
            workdir=args.workdir,
            keep_workdir=args.keep_workdir,
        )
    except Exception as exc:
        print(f"Flame Runner cluster e2e failed: {exc}", file=sys.stderr)
        return 1

    if args.json_output:
        print(json.dumps(asdict(result), sort_keys=True))
    else:
        print(format_result(result))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
