# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import flamepy.shim_pb2 as shim__pb2
import flamepy.types_pb2 as types__pb2


class InstanceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnSessionEnter = channel.unary_unary(
                '/flame.Instance/OnSessionEnter',
                request_serializer=shim__pb2.SessionContext.SerializeToString,
                response_deserializer=types__pb2.Result.FromString,
                )
        self.OnTaskInvoke = channel.unary_unary(
                '/flame.Instance/OnTaskInvoke',
                request_serializer=shim__pb2.TaskContext.SerializeToString,
                response_deserializer=types__pb2.TaskResult.FromString,
                )
        self.OnSessionLeave = channel.unary_unary(
                '/flame.Instance/OnSessionLeave',
                request_serializer=types__pb2.EmptyRequest.SerializeToString,
                response_deserializer=types__pb2.Result.FromString,
                )


class InstanceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OnSessionEnter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnTaskInvoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnSessionLeave(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InstanceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnSessionEnter': grpc.unary_unary_rpc_method_handler(
                    servicer.OnSessionEnter,
                    request_deserializer=shim__pb2.SessionContext.FromString,
                    response_serializer=types__pb2.Result.SerializeToString,
            ),
            'OnTaskInvoke': grpc.unary_unary_rpc_method_handler(
                    servicer.OnTaskInvoke,
                    request_deserializer=shim__pb2.TaskContext.FromString,
                    response_serializer=types__pb2.TaskResult.SerializeToString,
            ),
            'OnSessionLeave': grpc.unary_unary_rpc_method_handler(
                    servicer.OnSessionLeave,
                    request_deserializer=types__pb2.EmptyRequest.FromString,
                    response_serializer=types__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flame.Instance', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Instance(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OnSessionEnter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flame.Instance/OnSessionEnter',
            shim__pb2.SessionContext.SerializeToString,
            types__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnTaskInvoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flame.Instance/OnTaskInvoke',
            shim__pb2.TaskContext.SerializeToString,
            types__pb2.TaskResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnSessionLeave(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flame.Instance/OnSessionLeave',
            types__pb2.EmptyRequest.SerializeToString,
            types__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
