FROM rust:1.88 AS builder

WORKDIR /usr/src/flame
COPY . .

RUN apt-get update && apt-get install -y protobuf-compiler pkg-config libssl-dev
RUN cargo install --path ./object_cache

FROM ubuntu:24.04

RUN mkdir -p /usr/local/flame/bin
RUN mkdir -p /var/lib/flame/cache
WORKDIR /usr/local/flame

COPY --from=builder /usr/local/cargo/bin/flame-cache /usr/local/flame/bin/flame-cache

RUN chmod +x /usr/local/flame/bin/*

ENTRYPOINT ["/usr/local/flame/bin/flame-cache"]
