[project]
name = "crawler"
version = "0.1.0"
description = "Crawler Application"
dependencies = [
  "requests",
  "markitdown",
  "beautifulsoup4",
  "flamepy",
]

[tool.uv.sources]
# flamepy = { path = "../../../../sdk/python" }
flamepy = { path = "/usr/local/flame/sdk/python" }